Repository talktodo-v2/talktodo-client, pull requests merged in 2025-07, with the labels that each got.

#37 env : 스토리북 배포
  .github/workflows/chromatic.yml
  package.json
  src/components/toast/Toast.stories.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  vitest.config.ts
Labels: 🔧env

#40 env: 의존성 설치
  package.json
Labels: 🔧env

#51 fix: SVG 속성(pascal‑case → camelCase) 일괄 수정
  package.json
  public/icon/image.svg
  src/components/layout/Icons/Completed.tsx
  src/components/layout/Icons/FoldLeft.tsx
  src/components/layout/Icons/FoldRight.tsx
  src/components/layout/Icons/Plus.tsx
  src/components/layout/Icons/Profile.tsx
  src/components/ui/icons/AddIcon.tsx
  src/components/ui/icons/CheckIcon.tsx
  src/components/ui/icons/DeleteIcon.tsx
  src/task/components/card/TaskCard/TaskCard.stories.tsx
  src/task/components/card/TaskCard/TaskCard.tsx
  src/task/components/common/icons/checkIcon/CheckIcon.tsx
  src/task/components/common/icons/memoIcon/MemoIcon.tsx
  src/utils/cn.ts
Labels: ✏️chore

#58 feat: 아이콘 배럴 파일로 경로 정리
  src/task/components/TaskCard/layouts/RectangleTaskCard.tsx
  src/task/components/TaskCard/layouts/SquareTaskCard.tsx
  src/task/components/TaskCard/layouts/TimelineTaskCard.tsx
  src/task/components/common/icons/index.ts
Labels: ✏️chore

#60 feat: 목표 카드(GoalCard) 컴포넌트 추가
  public/icon/Flag.tsx
  src/mocks/testHandlers/tasksTest.tsx
  src/mocks/todoMockData/Goals.ts
  src/styles/theme.css
  src/task/components/TaskCard/TaskCard.stories.tsx
  src/task/components/TaskCard/TaskCard.tsx
  src/task/components/TaskCard/TaskCard.types.ts
  src/task/components/TaskCard/layouts/GoalCard.tsx
  src/task/components/TaskCard/layouts/RectangleTaskCard.tsx
  src/task/components/TaskCard/layouts/SquareTaskCard.tsx
  src/task/components/TaskCard/layouts/TimelineTaskCard.tsx
  src/task/components/common/Card/BaseCard.stories.tsx
  src/task/components/common/Card/BaseCard.tsx
  src/task/components/common/GoalProgressBar/GoalProgressBar.stories.tsx
  src/task/components/common/GoalProgressBar/GoalProgressBar.tsx
  src/task/components/common/GoalProgressBar/hooks/ProgressViewModel.test.ts
  src/task/components/common/GoalProgressBar/hooks/ProgressViewModel.tsx
Labels: ✨feature

#73 env : 불필요한 의존성을 제거합니다.
  package-lock.json
  package.json
  src/shared/components/Toast/Toast.tsx
Labels: 🔧env

#74 env: 의존성 설치
  package-lock.json
  package.json
Labels: 🔧env

#76 env: 의존성 설치
  package-lock.json
  package.json
Labels: 🔧env

#82 env: framer-motion 설치
  package-lock.json
  package.json
Labels: 🔧env

#79 feat : task mock 작성
  src/app/(test)/tasks-test/page.tsx
  src/shared/components/Dropdown/Dropdown.tsx
  src/shared/components/Form/MemoField/MemoField.tsx
  src/shared/components/Form/TaskField/TaskField.tsx
  src/shared/components/Select/SelectPriority.stories.tsx
  src/shared/components/Select/SelectPriority.tsx
  src/shared/lib/api/api.ts
  src/shared/lib/api/apiBuilder.ts
  src/shared/mocks/constants/index.ts
  src/shared/mocks/mockData/taskMockData.ts
  src/shared/mocks/testHandlers/tasksTest.tsx
  src/shared/types/api.ts
  src/shared/types/icon.ts
  src/shared/types/prioity.ts
  src/task/components/TaskForm/TaskForm.tsx
  src/task/components/common/LabelPriority/LabelPriority.tsx
  src/task/lib/taskApi.ts
  src/task/types/index.ts
  src/task/types/reponse/index.ts
  src/task/types/reponse/task-response.ts
  src/task/types/request/index.ts
  src/task/types/request/task-request.ts
Labels: ✨feature
